name: open_stop
description: 'Next Stop: Accessibility'

# Required in order to use git and path dependencies
publish_to: 'none'

version: 0.1.2+3

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^0.14.0
  geolocator: ^8.2.1
  latlong2: ^0.8.0
  vector_math: ^2.1.1
  animated_location_indicator:
    git:
      url: https://github.com/OPENER-next/animated_location_indicator.git
  animated_marker_layer:
    git:
      url: https://github.com/OPENER-next/animated_marker_layer.git
  osm_api:
    git:
      url: https://github.com/OPENER-next/osm_api.git
  collection: ^1.16.0
  dio: ^4.0.0
  provider: ^6.0.1
  shared_preferences: ^2.0.7
  flutter_secure_storage: ^5.0.2
  url_launcher: ^6.0.17
  flutter_appauth: ^2.2.0
  community_material_icon: ^5.9.55
  flutter_markdown: ^0.6.9
  nvbw_open_data:
    path: ./dependencies/nvbw_open_data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0
  nock: ^1.2.0
  build_runner: ^2.1.7
  build_version: ^2.0.0

# Use latest flutter map from github till a new version is released on pub.dev
dependency_overrides:
  flutter_map:
    git:
      url: https://github.com/fleaflet/flutter_map.git
      ref: b2437973d7cab12febb5f6c434c8a1612550cea3

flutter:
  fonts:
    - family: MaterialDesignIconFont
      fonts:
        - asset: packages/community_material_icon/fonts/materialdesignicons-webfont.ttf
  assets:
    - PRIVACY_POLICY.md
    - assets/images/
    - assets/images/onboarding/
    - assets/images/logos/
    - assets/images/questions/
    - assets/datasets/question_catalog.json
    - assets/datasets/map_feature_collection.json
  # The following line ensures that the Material Icons font is included
  uses-material-design: true

flutter_icons:
  image_path_android: 'assets/images/app_icon_android.png'
  image_path_ios: 'assets/images/app_icon_ios.png'
  adaptive_icon_foreground: 'assets/images/app_icon_adaptive_foreground.png'
  adaptive_icon_background: '#ffcd40'
  android: true
  ios: true
