name: open_stop
description: 'Next Stop: Accessibility'

# Required in order to use git and path dependencies
publish_to: 'none'

version: 0.4.1+11

environment:
  sdk: ">=2.17.1 <3.0.0"
  # The Flutter version is read in different build scripts and is used to setup the appropriate flutter toolkit.
  # The build processes cannot handle range notations like >=2.17.1 <3.0.0 or ^3.7.0.
  # Therefore it is important to always specify a fixed flutter version in that format: [0-9]+.[0-9]+.[0-9]+
  flutter: 3.7.9

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^3.1.0
  geolocator: ^9.0.2
  latlong2: ^0.8.0
  vector_math: ^2.1.4
  polylabel: ^1.0.1
  supercluster: ^2.1.0
  animated_location_indicator:
    git:
      url: https://github.com/OPENER-next/animated_location_indicator.git
  animated_marker_layer:
    git:
      url: https://github.com/OPENER-next/animated_marker_layer.git
  osm_api:
    git:
      url: https://github.com/OPENER-next/osm_api.git
  temaki_flutter:
    git:
      url: https://github.com/OPENER-next/temaki_flutter.git
  collection: ^1.17.0
  dio: ^5.1.0
  provider: ^6.0.5
  shared_preferences: ^2.0.20
  flutter_secure_storage: ^8.0.0
  url_launcher: ^6.0.17
  flutter_web_auth: ^0.5.0
  material_design_icons_flutter: ^6.0.7096
  flutter_markdown: ^0.6.14
  nvbw_open_data:
    path: ./dependencies/nvbw_open_data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0
  nock: ^1.2.1
  build_runner: ^2.3.3
  build_version: ^2.1.1

flutter:
  assets:
    - PRIVACY_POLICY.md
    - assets/images/
    - assets/images/onboarding/
    - assets/images/logos/
    - assets/images/questions/
    - assets/datasets/question_catalog.json
    - assets/datasets/map_feature_collection.json
  # The following line ensures that the Material Icons font is included
  uses-material-design: true

flutter_icons:
  image_path_android: 'assets/images/app_icon_android.png'
  image_path_ios: 'assets/images/app_icon_ios.png'

  adaptive_icon_foreground: 'assets/images/app_icon_adaptive_foreground.png'
  adaptive_icon_background: '#ffcd40'
  android: true
  ios: true
  web:
    generate: true
    image_path: 'assets/images/app_icon_ios.png'
    background-color: '#ffcd40'
    theme-color: '#ffcd40'
