name: Code Validation

on:
  push:
  pull_request:

  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    # Trigger an action on push OR pull request but not both. The second event will be skipped.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run shared environment setup steps
      uses: ./.github/actions/environment_setup

    - name: Run static analysis and style guideline checks
      run: flutter analyze
