name: Code Validation

on:
  push:
  pull_request:

  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter --version

    - run: flutter pub get
    # Run static analysis and style guideline checks
    - run: flutter analyze
