name: JSON Validation

on:
  push:

  pull_request:

  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /assets/questions/question_catalog_schema.json
          INPUT_JSONS: /assets/questions/question_catalog.json
