name: JSON Validation

on:
  push:
    paths:
      - '**/question_catalog.json'
      - '**/question_catalog_schema.json'
      - '**/map_feature_collection.json'
      - '**/map_feature_collection_schema.json'
      - '**/osm_condition_schema.json'
  pull_request:
    paths:
      - '**/question_catalog.json'
      - '**/question_catalog_schema.json'
      - '**/map_feature_collection.json'
      - '**/map_feature_collection_schema.json'
      - '**/osm_condition_schema.json'

  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Validate questions JSON
        uses: cardinalby/schema-validator-action@v1
        with:
          file: 'assets/datasets/question_catalog.json'
          schema: 'assets/datasets/question_catalog_schema.json'

      - name: Validate map features JSON
        uses: cardinalby/schema-validator-action@v1
        with:
          file: 'assets/datasets/map_feature_collection_schema.json'
          schema: 'assets/datasets/map_feature_collection.json'
