name: JSON Validation

on:
  push:

  pull_request:

  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          
      - name: Install npm
        run: npm install
        
      - name: Install ajv-cli
        run: npm install -g ajv-cli
        
      - name: Validate JSON
        run: |
          ajv validate 
          -s assets/questions/question_catalog_schema.json
          -d assets/questions/question_catalog.json
          -m https://json-schema.org/draft/2020-12/schema
