name: test

on:
  # Trigger workflow when new tag is pushed.
  push:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent build and deployment workflow
concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  build_web:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install yq
      run: pip3 install yq

    - name: Read Flutter version from pubspec.yaml
      id: flutterVersion
      run: |
        echo "result=$(yq -r .environment.flutter pubspec.yaml)" >> $GITHUB_OUTPUT 

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.flutterVersion.outputs.result }}
        channel: 'stable'

    - name: Download pub dependencies
      run: flutter pub get

    - name: Run build_runner
      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Build web
      run: >-
        flutter build web
        --dart-define=THUNDERFOREST_API_KEY=${{ secrets.THUNDERFOREST_API_KEY }}
        --dart-define=IS_RELEASE=true
        
    - name: Convert Markdown to HTML
      uses: natescherer/markdown-to-html-with-github-style-action@v1
      with:
        path: PRIVACY_POLICY.md
        outputpath: build/web

    - name: Upload web artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'build/web'

